#spring:
#  profiles:
#    active: dev
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.0.145:3306/vinux_sso?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: vinux
#    
#
#spring:
#    data:
#        elasticsearch:
#            cluster-name: nini
#            cluster-nodes: 192.168.21.1:9300
#            local: false
#            repositories:
#                enable: true   
app:
  name: abv

#session 过期时间(单位为”秒“)。如果参数不是60的整数倍，会转换成60的整数倍；不满一分钟，会转换为60秒。
server: 
  name: www.chnghx.com
  session: 
    timeout: 60
  tomcat: 
    uri-encoding: UTF-8
#解决中文乱码
banner: 
  charset: UTF-8

spring:
  application: 
    name: chnghx #应用名称
  profiles: #多环境配置文件激活属性
    active: dev
  http: 
    encoding: 
      charset: UTF-8
    enabled: true
    force: true
  messages:
    encoding: UTF-8
  cloud: #cloud 配置
    config: 
      discovery: 
        enabled: true #启动服务发现的功能，开启了才能调用其它服务
        serviceId: eureka-server #发现的服务的名字--对应注测中心的服务名字 
    client: 
      hostname: localhost #客户端host
      
  datasource: #数据源配置
    mysql: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.182:3306/chnghx?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: mysql
#    sqlite: 
#      driver-class-name: org.sqlite.JDBC
#      url: jdbc:sqlite::resource:chnghx.db
#      username: 
#      password: 
  jpa: 
    show-sql: true
    
  redis: #### redis 配置
    database: 0 #Redis数据库索引（默认为0）
    host: 192.168.0.28 # Redis服务器地址
    password: 
    port: 6379
    timeout: 0 # 连接超时时间（毫秒）
    pool: 
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#thymeleaf 配置
  thymeleaf: 
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    #页面缓存
    cache: false
#    mode: LEGACYHTML5
#freemarker 配置
#spring.mvc.view.prefix=/templates/
#spring.mvc.view.suffix=.ftl


#开启Hystrix的功能。Feign在新版本中默认是没有开启Hystrix的功能
feign: 
  hystrix: 
    enabled: true



com: 
  chnghx: 
    security: com.chnghx.com
    random: 
      #随机字符串
      v1: ${random.value} 
      #10以内的随机数
      v2: ${random.int(10)}
      #10-20的随机数
      v3: ${random.int[10,20]}

mybatis: 
  type-aliases-package: com.demo.entity
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: org.spring.springboot.domain
  mapperLocations: classpath:mapper/*.xml

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#文件上传
multipart: 
  #文件最大限制
  maxFileSize: 50Mb
  #所有文件总大小限制
  maxRequestSize: 50Mb

logging:
  config: classpath:log4j2.yml

  
eureka: 
  instance: 
    hostname: localhost
    port: 8761
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
    prefer-ip-address: false #在注册中心url中不显示IP地址前缀
  client: 
    serviceUrl: #指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
      
member: 
  login: http://www.vinuxmembers.com/open/request/pc/login.vhtml?return_url=http://org.vinux.com/open/member/login.vhtml
  
